get_ipython().run_line_magic('pip', 'install -q pickleshare')
get_ipython().run_line_magic('pip', 'install -q notebook')
get_ipython().run_line_magic('pip', 'install -q keyring')
get_ipython().run_line_magic('pip', 'install -q keyrings.alt')
get_ipython().run_line_magic('pip', 'install -q dill')
get_ipython().run_line_magic('pip', 'install -q ipynbname')
get_ipython().run_line_magic('pip', 'install -q ipylab')
get_ipython().run_line_magic('pip', 'install -q lxml')