install.packages('reticulate')
library('reticulate')
library("future")
plan(multisession)
py_require(c('pickleshare'))
py_require(c('notebook'))
py_require(c('keyring'))
py_require(c('dill'))
py_require(c('ipynbname'))
py_require(c('ipylab'))
py_require(c('lxml'))
py_require(c('keyrings.alt'))
py_require(c('bs4'))
py_require(c('nbformat'))
py_require(c('keyring'))
asyncio <- import("asyncio")